"""Second migration

Revision ID: 9c2acce7f138
Revises: 19d6e7a3e7fc
Create Date: 2025-10-13 21:31:42.233788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2acce7f138'
down_revision: Union[str, None] = '19d6e7a3e7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('products', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'slug')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
